### ISSUE TITLE
Escape special chars in JS (like quotes)

### ISSUE THREAD

**Issue by denisbertrandbe** [madebykind/craft.labelenvironment#7]
Hi,

I think it could be great to escape specials chars of $fullText when including JS global CRAFT_ENVIRONMENT_LABELin EnvironmentLabelService.php.

I had an JS error which affect backend of CraftCMS after writing something like (in french) : 

> Vous n'êtes pas sur le site de production

`
craft()->templates->includeJs("window.CRAFT_ENVIRONMENT_LABEL = '" . $fullText . "';");
`

Kind regards,

Denis

**Comment by tomdavies** [comment]
@justdoweb-be thanks for reporting this. 

Yay character encoding :)

I'm actually planning on removing the JS global in the [next major release](https://github.com/madebykind/craft.labelenvironment/pull/6). Is it something you're actively using or just that it happens to throw an error?

**Comment by denisbertrandbe** [comment]
No, I don’t use the JS global. It just throw an blocking error.

**Comment by tomdavies** [comment]
@justdoweb-be should be fixed in the 2.1.1 release I just pushed - just wrapped the label string in `json_encode.
